
version: "1"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore
    networks:
      springboot-mysql-net: null
  backend-java:
    image: docker.io/saran0809/demo-devops:latest
    container_name: demo-devops
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
