
version: "1"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    volumes:
      - C:/Users/Aaludra_05/Documents/db:/var/lib/mysql
    ports:
     - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore
  backend-java:
    image: docker.io/saran0809/demo-devops:latest
    restart: always
    container_name: demo-devops
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306

    
